name: first-pipeline
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  first-job:
    name: "my first job"
    runs-on: ubuntu-latest
    steps:
      - name: "My first action"
        run: echo "hello world"
      - name: "Second Action"
        run: echo "second action"
        
